# Generated by Django 5.2 on 2026-07-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('setting_type', models.CharField(choices=[('general', 'General'), ('branding', 'Branding'), ('content', 'Content Pages'), ('contact', 'Contact Info'), ('social', 'Social Media'), ('seo', 'SEO')], default='general', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['setting_type', 'key'],
            },
        ),
    ]
