# Generated by Django 5.2 on 2026-07-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFileSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='site_settings/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site File Setting',
                'verbose_name_plural': 'Site File Settings',
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='setting_type',
            field=models.CharField(choices=[('general', 'General'), ('branding', 'Branding'), ('content', 'Content Pages'), ('contact', 'Contact Info'), ('social', 'Social Media'), ('seo', 'SEO'), ('faq', 'FAQ Management')], default='general', max_length=20),
        ),
    ]
