# Generated by Django 5.2 on 2026-08-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text="Program Director's digital signature for certificates", null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text="Instructor's digital signature for certificates", null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='access_level',
            field=models.IntegerField(default=1, help_text='1=Basic, 2=Manager, 3=Super Admin'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
