# Generated by Django 5.2 on 2026-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text="Instructor's digital signature for certificates", null=True, upload_to='signatures/'),
        ),
    ]
