# Generated by Django 5.2 on 2026-08-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_signature_customuser_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload your digital signature for certificates (PNG with transparent background recommended)', null=True, upload_to='instructor_signatures/'),
        ),
    ]
