# Generated by Django 5.2 on 2026-08-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_instructorprofile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text="Program Director's digital signature for certificates (PNG with transparent background recommended)", null=True, upload_to='admin_signatures/'),
        ),
    ]
