# Generated by Django 5.2 on 2026-07-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instructorprofile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text="Program Director's digital signature for certificates", null=True, upload_to='signatures/'),
        ),
    ]
