# Generated by Django 5.2 on 2026-10-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminprofile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Required. Enter a valid phone number.', max_length=20, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
