# Generated by Django 5.2 on 2026-07-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminprofile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='access_level',
            field=models.IntegerField(default=1, help_text='1=Basic, 2=Manager, 3=Super Admin'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
