# Generated by Django 5.2 on 2026-08-06 19:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class e.g. 'fas fa-shield-alt'", max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, help_text='Brief description for course cards', max_length=500, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('featured_video', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube/Vimeo trailer link', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='all', max_length=20)),
                ('duration', models.CharField(blank=True, help_text="e.g., '12 Weeks' or '24 Hours'", max_length=100, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('requirements', models.TextField(blank=True, help_text='Prerequisites for the course', null=True)),
                ('what_you_learn', models.TextField(blank=True, help_text='Learning outcomes (one per line)', null=True)),
                ('has_certificate', models.BooleanField(default=False)),
                ('certificate_template', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('review', 'In Review')], default='draft', max_length=20)),
                ('badge', models.CharField(choices=[('none', 'None'), ('bestseller', '🔥 Bestseller'), ('trending', '📈 Trending'), ('new', '✨ New'), ('featured', '⭐ Featured Course of the Month')], default='none', help_text='Badge displayed on course card (Bestseller, Trending, New, or Featured)', max_length=20)),
                ('badge_updated_at', models.DateTimeField(blank=True, help_text='When the badge was last updated', null=True)),
                ('featured_at', models.DateTimeField(blank=True, help_text='When the course was marked as featured', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'user_type': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Announcement',
                'verbose_name_plural': 'Course Announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('paused', 'Paused')], default='active', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', through='courses.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeaturedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_free_preview', models.BooleanField(default=False, help_text='Allow non-enrolled students to preview')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('video_url', 'Video URL (YouTube/Vimeo)'), ('text', 'Text/Article'), ('pdf', 'PDF Document'), ('quiz', 'Quiz/Assessment'), ('assignment', 'Assignment'), ('code', 'Code Exercise'), ('slides', 'Presentation Slides')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lesson_thumbnails/')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='lesson_videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', max_length=500, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Upload PDF document', null=True, upload_to='lesson_pdfs/')),
                ('text_content', models.TextField(blank=True, help_text='Rich text content for text/quiz types', null=True)),
                ('allow_download', models.BooleanField(default=False, help_text='Allow students to download this content')),
                ('time_duration', models.DurationField(blank=True, help_text='e.g., 00:15:30 for 15 minutes 30 seconds', null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('quiz_data', models.JSONField(blank=True, help_text='Quiz questions and answers in JSON format', null=True)),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='Passing percentage for quizzes')),
                ('assignment_instructions', models.TextField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_preview', models.BooleanField(default=False, help_text='Allow preview without enrollment')),
                ('is_required', models.BooleanField(default=True, help_text='Must complete to finish lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Content',
                'verbose_name_plural': 'Lesson Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.DurationField(default=datetime.timedelta)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
            },
        ),
        migrations.CreateModel(
            name='TopPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_picks', to='courses.course')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('is_recommended', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_cou_status_158bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='courses_cou_instruc_d2e347_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_cou_categor_108713_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['badge'], name='courses_cou_badge_94e6ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('student', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='toppick',
            unique_together={('course', 'is_active')},
        ),
    ]
