# Generated by Django 5.2 on 2026-08-23 15:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='what_you_learn',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text="Full course description including requirements, what you'll learn, and course details", null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price in GBP (£)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in GBP (£)', max_digits=10),
        ),
    ]
