# Generated by Django 5.2 on 2026-07-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='Allow students to download this content'),
        ),
    ]
