# Generated by Django 6.1 on 2026-08-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quizanswer_quiz_quizattempt_quizquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='quiz_data',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='content',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(default=1, help_text='The lesson this quiz belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions_per_attempt',
            field=models.PositiveIntegerField(blank=True, help_text='Number of random questions to show (leave empty to show all)', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_answers',
            field=models.BooleanField(default=True, help_text='Randomize answer options for each question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_questions',
            field=models.BooleanField(default=True, help_text='Randomize question order for each attempt'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_correct_answers',
            field=models.BooleanField(default=True, help_text='Show correct answers after submission'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quizanswerrecord',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('video_url', 'Video URL (YouTube/Vimeo)'), ('text', 'Text/Article'), ('pdf', 'PDF Document'), ('assignment', 'Assignment'), ('code', 'Code Exercise'), ('slides', 'Presentation Slides')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='text_content',
            field=models.TextField(blank=True, help_text='Rich text content for text/code types', null=True),
        ),
    ]
