# Generated by Django 5.2 on 2026-10-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_finalexamanswer_finalexam_finalexamattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='total_pages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
