# Generated by Django 5.2 on 2026-08-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum purchase amount in GBP (£)', max_digits=10),
        ),
    ]
