# Generated by Django 5.2 on 2026-07-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('review_text', models.TextField()),
                ('designation', models.CharField(blank=True, help_text='e.g., Product Designer, USA', max_length=200, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before displaying')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Review',
                'verbose_name_plural': 'Site Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
